### ISSUE TITLE
Ошибка "Workspace not found"

### ISSUE THREAD

**Issue by eshevlyakova** [atls-academy/eshevlyakova.github.io#12]
### Скоуп

Установление зависимостей

### Описание

При команде `yarn` появляется ошибка

### Контекст

Проблема исчезает если добавить папку data с существующего проекта

### Воспроизведение

1. Запускаю команду `yarn`
2. Ошибка

### Ожидаемое поведение

Все пакеты должны установиться без ошибок

### Медиа-материалы

<img width="1274" alt="Снимок экрана 2022-09-14 в 19 11 15" src="https://user-images.githubusercontent.com/79781486/190206826-579701e2-7b45-4e78-917f-f5accfd1ff1f.png">

### Действия

1. Удалила папку data
2. Запустила команду yarn

### Вопрос

1. Как исправить появившуюся ошибку и из-за чего она появилась?

**Comment by TFK70** [comment]
@eshevlyakova 

"Workspace not found" - воркспейс не найден

`@globals/data` - это воркспейс, ты его удаляешь и этого воркспейса нет

Когда этого воркспейса нет, но он указан где-то в зависимостях - появляется такая ошибка

**Comment by eshevlyakova** [comment]
Ошибка устранена, в одном из файлов package.json (landing/app) была зависимость `@globals/data`
