### ISSUE TITLE
Кастомизация компонента Layout

### ISSUE THREAD

**Issue by eshevlyakova** [atls-academy/eshevlyakova.github.io#13]
### Скоуп

Добавление ширины для Layout

### Описание

Из готового компонента Layout я хочу сделать контейнер, для этого нужно добавить ширину для всех компонентов Layout

### Воспроизведение

1. Я хотела изменить стили локально, я иду в ui/layout/src/ но у меня там только файл index.ts и сам пакет скачивается

### Ожидаемое поведение

Компонент Layout имеет нужную ширину и я могу использовать его вместо container

### Действия

-

### Вопрос

1. Как я могу добавить стили для всех компонентов Layout?

**Comment by eshevlyakova** [comment]
@eshevlyakova @TFK70 поможешь пожалуйста со стилизацией Layout. Я вопрос по форме составила

**Comment by TFK70** [comment]
@eshevlyakova Ширину точно не нужно ставить для всех лейаутов. Если тебе действительно будет проще сделать какой-то общий контейнер - создай его на базе лейаута с помощью стайлед: const Container = styled(Layout)({ width: 228 })

**Comment by eshevlyakova** [comment]
@TFK70 
А я могу писать media запросы внутри `({ width: 228 })` ?

**Comment by TorinAsakura** [comment]
@eshevlyakova а зачем тебе media запросы?

**Comment by eshevlyakova** [comment]
@TorinAsakura 
Адаптив для контейнера

**Comment by TFK70** [comment]
@eshevlyakova https://styled-system.com/responsive-styles/

**Comment by eshevlyakova** [comment]
@TFK70 
> https://styled-system.com/responsive-styles/

А куда помещать файл index.js, в landing/fragments/name-fragment/src/ или в корень проекта?
```js
const breakpoints = ['40em', '52em', '64em', '80em']

breakpoints.sm = breakpoints[0]
breakpoints.md = breakpoints[1]
breakpoints.lg = breakpoints[2]
breakpoints.xl = breakpoints[3]

export default {
  breakpoints,
}
```

**Comment by TFK70** [comment]
@eshevlyakova - Что за index js?
- Почему js когда у нас везде ts?
- Что в нём находится?
- Что это за код?
- У нас где-то подобное на проектах было?

**Comment by eshevlyakova** [comment]
@TFK70 
Я хочу создать свои breakpoints с помощью массива. В статье https://styled-system.com/responsive-styles/#using-objects сказано что для этого нужно создать файл index.js (в нашем случае index.ts) и поместить в него следующий код:
```js
const breakpoints = ['40em', '52em', '64em', '80em']

breakpoints.sm = breakpoints[0]
breakpoints.md = breakpoints[1]
breakpoints.lg = breakpoints[2]
breakpoints.xl = breakpoints[3]

export default {
  breakpoints,
}
```
Но я не понимаю куда поместить этот файл, в landing/fragments/name-fragment/src/ или в корень проекта?

**Comment by TFK70** [comment]
@eshevlyakova обрати внимание на [это](https://styled-system.com/responsive-styles/#what-it-does). Тебе не нужно создавать никаких своих брейкпоинтов, либа сама их генерит

И снова повторюсь - где что-то подобное ты видела в примерах, которые я кидал? Там между прочим тоже есть мобильная версия приложения, и никаких кастомных брейкпоинтов там не было

**Comment by eshevlyakova** [comment]
@TFK70 
> обрати внимание на [это](https://styled-system.com/responsive-styles/#what-it-does).

Я поняла как работает расчет ширины, но не могу понять как указывать к примеру fontSize? Если писать px, то будет ошибка

**Comment by eshevlyakova** [comment]
Ошибка устранена, я использовала другой подход (сделала адаптив на основе уже сгенерированных брекпоинтов)
