### ISSUE TITLE
Фон из темы для компонента Background

### ISSUE THREAD

**Issue by eshevlyakova** [atls-academy/eshevlyakova.github.io#19]
### Скоуп

Добавление фона из темы для компонента Background

### Описание

Не могу понять, как добавить фон из темы (файл backgrounds.ts) для компонента Background (он разный на мобилке и декстопе)

### Контекст

[Коммит](https://github.com/atls-academy/eshevlyakova.github.io/pull/17/commits/6b31551d63c6992385a26fc77ac754a6985617d2)

### Воспроизведение

1. Запустить `yarn workspace @landing/renderer-entrypoint run dev`
2. Открывается главная страница и видим, что нет фона для шапки и 1 секции

### Ожидаемое поведение

Фон подгружается из темы для данного компонента, причем для каждого разрешения свой фон

### Медиа-материалы

<img width="1279" alt="Снимок экрана 2022-10-19 в 12 52 29" src="https://user-images.githubusercontent.com/79781486/196658822-07f0475e-1bef-4b2c-ad9c-a9dd4f0a4f0a.png">

### Действия

1. Я создаю компонент Background (landing/pages/index-page/src/index.page.tsx) и с помощью @emotion/styled и styled-system добавляю для элемента css-свойства фона
3. Использую этот компонент и в свойстве background прописываю названия фонов для разных разрешений из файла темы backgrounds.ts

### Вопрос

1. Как сделать так, чтобы в компоненте Background для свойства background фон подгружался из темы файла backgrounds.ts? 
То есть чтобы этот код был рабочим: `background={['mobileBannerBlockBackground', 'mobileBannerBlockBackground', 'bannerBlockBackground']}`

**Comment by TFK70** [comment]
@eshevlyakova я так понимаю ты это спрашиваешь потому что ты "сделала правильно, но у тебя ничего не работает"

Тут не просто так есть секции с материалами, логами и воспроизведением, которое у тебя заполнено неправильно, все примеры ведь даже в плейсхолдерах таски есть, почему ты им не следуешь?

Во-первых, дай какие-то материалы, которые отображают твою ошибку, логи из консоли что он не может что-то получить
Во-вторых, заполни воспроизведение, мне нужны шаги чтобы воспроизвести твою ошибку
В-третьих, в поле контекст указывай пр/коммит, не пропускай поля, они не для красоты ведь тут

**Comment by eshevlyakova** [comment]
@TFK70 
> Во-первых, дай какие-то материалы, которые отображают твою ошибку, логи из консоли что он не может что-то получить

Ошибки нет, просто фон не отображается
Остальные 2 пункта подправила

**Comment by TFK70** [comment]
@eshevlyakova 

> Во-вторых, заполни воспроизведение, мне нужны шаги чтобы воспроизвести твою ошибку

Чем вот это `Данный компонент находится в landing/pages/index-page/src/index.page.tsx
Чтобы увидеть баг нужно запустить yarn workspace @landing/renderer-entrypoint run dev`  похоже на вот это?

![image](https://user-images.githubusercontent.com/62806448/196656953-6c49adba-8b40-47dc-9e3a-41437a36865e.png)

Я как должен догадаться на какой компонент мне смотреть?

> Ошибки нет, просто фон не отображается

Не надо об этом текстом писать, в шаблоне есть секция медиа-материалы

**Comment by eshevlyakova** [comment]
@TFK70 исправила

**Comment by TFK70** [comment]
@eshevlyakova 

> То есть чтобы этот код был рабочим: background={['mobileBannerBlockBackground', 'mobileBannerBlockBackground', 'bannerBlockBackground']}

Дай ссылку на эту строку в коммите

**Comment by eshevlyakova** [comment]
@TFK70 
https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-2/landing/pages/index-page/src/index.page.tsx#L18

**Comment by TFK70** [comment]
@eshevlyakova у тебя же есть пример - https://github.com/atls-academy/gochicus.github.io/blob/master/practice/web-diary/ui/background/src/Background.tsx#L6

**Comment by eshevlyakova** [comment]
@TFK70 
Я делала так. Все работает если компонент использовать так:
```tsx
<Background gradient='bannerBlockBackground' />
```
то есть без адаптива. Но если я пишу так, то опять фон исчезает:
```tsx
<Background gradient={[
          'mobileBannerBlockBackground',
          'mobileBannerBlockBackground',
          'bannerBlockBackground'
        ]}
      >
```
Как это можно исправить?

**Comment by TFK70** [comment]
@eshevlyakova а почему у тебя **цвет** называется `mobileBlockBackground`?

Ты действительно не видишь разницы между тем, как называешь цвета ты и как это делается у нас?

Вот скажи, какой из этих цветов мобильный, а какой десктопный:

![image](https://user-images.githubusercontent.com/62806448/196666558-9f1a9e88-3d23-4ec8-b961-3f2d9581289c.png)

![image](https://user-images.githubusercontent.com/62806448/196666607-adf20ccf-8f79-4ea3-a971-f2ab91cfccdf.png)

![image](https://user-images.githubusercontent.com/62806448/196666649-e7891edf-a24a-4b85-9b93-763fdb5f87ad.png)

А насчёт адаптива - реализуй его через `display={['none', 'none', 'flex']}` и тп, если у тебя нет возможности использовать функционал styled system для нужного тебе пропа

**Comment by eshevlyakova** [comment]
Ошибка решена, реализовала адаптив с помощью css-свойства display
