### ISSUE TITLE
Ошибка: Module not found: Can't resolve 'react'

### ISSUE THREAD

**Issue by eshevlyakova** [atls-academy/eshevlyakova.github.io#22]
### Скоуп

Добавление слайдера для фрагмента landing-section-courses

### Описание

При запуске сайта в консоли появляется ошибка и сам сайт не разворачивается (белый экран). Я гуглила эту ошибку и нашла, что это может быть из-за версии swiper и то, что нужно использоватть 6 его версию. Но это не помогло

### Контекст

[Коммит](https://github.com/atls-academy/eshevlyakova.github.io/commit/f1a6531cc05cdd5b6568820bee08b9b357f992be)

### Воспроизведение

1. Запустить yarn workspace @landing/renderer-entrypoint run dev
2. Открывается главная страница и видим белый экран
3. Если вернуться, то в консоли видим ошибку

### Ожидаемое поведение

Сайт разворачивается и на мобильной версии работает слайдер

### Логи

```shell
error - ../../../../.yarn/unplugged/swiper-npm-8.4.4-c63bd6daca/node_modules/swiper/react/context.js:1:0
Module not found: Can't resolve 'react'

Import trace for requested module:
../../../../.yarn/unplugged/swiper-npm-8.4.4-c63bd6daca/node_modules/swiper/react/swiper-react.js
../../../../.yarn/__virtual__/@atls-ui-parts-swiper-virtual-aa5f06b1e9/0/cache/@atls-ui-parts-swiper-npm-0.0.3-8c8f13c038-fd2de967ab.zip/node_modules/@atls-ui-parts/swiper/dist/swiper.js
../../../../.yarn/__virtual__/@atls-ui-parts-swiper-virtual-aa5f06b1e9/0/cache/@atls-ui-parts-swiper-npm-0.0.3-8c8f13c038-fd2de967ab.zip/node_modules/@atls-ui-parts/swiper/dist/index.js
../../../../.yarn/__virtual__/@ui-slider-virtual-4609eaf602/1/ui/slider/src/index.ts
../../../../.yarn/__virtual__/@landing-courses-fragment-virtual-ec1afc1627/1/landing/fragments/landing-section-courses/src/courses.component.tsx
../../../../.yarn/__virtual__/@landing-courses-fragment-virtual-ec1afc1627/1/landing/fragments/landing-section-courses/src/index.ts
../../../../.yarn/__virtual__/@landing-index-page-virtual-cc78e21148/1/landing/pages/index-page/src/index.page.tsx
../../../../.yarn/__virtual__/@landing-index-page-virtual-cc78e21148/1/landing/pages/index-page/src/index.ts
./pages/index.ts

https://nextjs.org/docs/messages/module-not-found
Could not find files for / in .next/build-manifest.json
Could not find files for / in .next/build-manifest.json
```

### Медиа-материалы

<img width="1274" alt="Снимок экрана 2022-10-26 в 13 29 29" src="https://user-images.githubusercontent.com/79781486/198003716-42555fc8-207d-47ce-9388-960830dae517.png">
<img width="1239" alt="Снимок экрана 2022-10-26 в 13 29 47" src="https://user-images.githubusercontent.com/79781486/198003772-c98e2103-085b-43d6-abea-18d976f2c64e.png">

### Действия

1. В папке ui я создаю пакет @ui/slider и копипастю все содержимое [отсюда](https://github.com/torin-asakura/misik/tree/master/ui/carousel)
2. Для фрагмента @landing/courses-fragment в package.json прописываю зависимости @ui/slider и swiper и запускаю команду yarn
3. В компоненте файла courses.component.tsx (@landing/courses-fragment) импортирую Swiper и SwiperSlide из пакета @ui/slider и использую

### Вопрос

Из-за чего появилась эта ошибка и как ее исправить?

**Comment by TFK70** [comment]
@eshevlyakova у тебя swiper не может получить доступ к реакту, потому что в твоём пакете не соблюдены [peerDependencies](https://github.com/atls/uikit/blob/master/ui-parts/swiper/package.json#L26)

Почитай про них тут - https://github.com/atls/uikit/wiki/%D0%A7%D1%82%D0%BE-%D1%82%D0%B0%D0%BA%D0%BE%D0%B5-peerDependencies

**Comment by eshevlyakova** [comment]
@TFK70 
> в твоём пакете не соблюдены [peerDependencies](https://github.com/atls/uikit/blob/master/ui-parts/swiper/package.json#L26)

То есть моя ошибка в dependencies пакета @ui/slider?

**Comment by TFK70** [comment]
> 

Ты поняла что я написал?

**Comment by eshevlyakova** [comment]
@TFK70 
Я поняла так, что в пакете @ui/slider не прописаны зависимости, которые указаны в peerDependencies пакета @atls-ui-parts/swiper

**Comment by TFK70** [comment]
> @TFK70 Я поняла так, что в пакете @ui/slider не прописаны зависимости, которые указаны в peerDependencies пакета @atls-ui-parts/swiper

Я ожидал либо "Да", либо "Нет + <вопрос>"

Ты от меня что сейчас ожидаешь?

**Comment by eshevlyakova** [comment]
@TFK70 
> Ты от меня что сейчас ожидаешь?

Правильно ли я поняла твое сообщение и если нет, то что не так

**Comment by TFK70** [comment]
> @TFK70
> 
> > Ты от меня что сейчас ожидаешь?
> 
> Правильно ли я поняла твое сообщение и если нет, то что не так

если поняла - фикси, если нет - задай вопрос

Ты должна инициативу проявлять, а не я

**Comment by eshevlyakova** [comment]
@TFK70 
> потому что в твоём пакете не соблюдены [peerDependencies](https://github.com/atls/uikit/blob/master/ui-parts/swiper/package.json#L26)

Что значит не соблюдены? Не указаны в dependencies?

**Comment by TFK70** [comment]
> @TFK70
> 
> > потому что в твоём пакете не соблюдены [peerDependencies](https://github.com/atls/uikit/blob/master/ui-parts/swiper/package.json#L26)
> 
> Что значит не соблюдены? Не указаны в dependencies?

Ты поняла что такое peerDependencies?

**Comment by eshevlyakova** [comment]
@TFK70 
Да, это позволяет дочерним пакетам, брать зависимости родителя, использовать родительскую копию (не создавая свои)

**Comment by TFK70** [comment]
@eshevlyakova увидел что у тебя все-таки есть все необходимые зависимости в пакете, это проблема на стороне  свайпера

У свайпера в зависимостях не указан react, чтобы починить это используй [packageExtensions](https://yarnpkg.com/configuration/yarnrc#packageExtensions) в `.yarnrc.yml`

**Comment by eshevlyakova** [comment]
Ошибка решена, для swiper добавила react зависимость с помощью packageExtensions
