### ISSUE TITLE
Ошибка TypeCheck

### ISSUE THREAD

**Issue by eshevlyakova** [atls-academy/eshevlyakova.github.io#23]
### Скоуп

Ошибка при проверка yarn check

### Описание

yarn typecheck выдает ошибку: Interface 'SwiperSlideProps' incorrectly extends interface 'HTMLAttributes<HTMLElement>'.

### Контекст

Swiper я использую только [в этом фрагменте](https://github.com/atls-academy/eshevlyakova.github.io/tree/feat/landing-step-3/landing/fragments/landing-section-courses)

### Воспроизведение

1. Заходим в корень проекта
2. В консоли запускаем yarn check

### Ожидаемое поведение

Проверка завершается без ошибок

### Логи

```shell
.yarn/unplugged/swiper-virtual-7d4bde7ac3/node_modules/swiper/react/swiper-react.d.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Interface 'SwiperSlideProps' incorrectly extends interface 'HTMLAttributes<HTMLElement>'.
➤ YN0000: │          Types of property 'children' are incompatible.
➤ YN0000: │            Type 'ReactNode | ((slideData: SlideData) => ReactNode)' is not assignable to type 'ReactNode'.
➤ YN0000: │              Type '(slideData: SlideData) => ReactNode' is not assignable to type 'ReactNode'.
➤ YN0000: │                Type '(slideData: SlideData) => ReactNode' is missing the following properties from type 'ReactPortal': key, children, type, props
```

### Действия

1. Добавляла в tsconfig.json: "skipLibCheck": true

### Вопрос

Как исправить эту ошибку?

**Comment by TFK70** [comment]
@eshevlyakova понимаешь суть ошибки? Из-за чего он ругается на SwiperSlideProps?

**Comment by eshevlyakova** [comment]
@TFK70 
Не очень

**Comment by TFK70** [comment]
> @TFK70 Не очень

Ну, тебя интересуют пока только первые 2 строчки:

```shell
➤ YN0000: │   Error: Interface 'SwiperSlideProps' incorrectly extends interface 'HTMLAttributes<HTMLElement>'.
➤ YN0000: │          Types of property 'children' are incompatible.
```

Ты вроде встречалась уже с такой ошибкой кстати. Попробуй на русском объяснить о чем тут говорится

**Comment by TFK70** [comment]
@eshevlyakova Интерфейс `SwiperSlideProps` неверное наследует интерфейс `HTMLAttributes<HTMLElement>`
Типы свойства `children` несовместимы

Говорит о чём-то?

**Comment by eshevlyakova** [comment]
@TFK70 
> Говорит о чём-то?

Не особо. Я понимаю о чем ты говоришь, но не до конца

**Comment by TFK70** [comment]
@eshevlyakova попробуй у себя в одном из проектых файлах сделать такую конструкцию и запустить typecheck:

```typescript
interface A {
  id: string | number
  props: Array<string>
}

interface B extends A {
  id: boolean
  name: string
}
```

**Comment by eshevlyakova** [comment]
@TFK70 
В консоли появилась эта ошибка:
```shell 
➤ YN0000: │   Error: Interface 'B' incorrectly extends interface 'A'.
➤ YN0000: │          Types of property 'id' are incompatible.
➤ YN0000: │            Type 'boolean' is not assignable to type 'string | number'.
```
Она появилась из-за того, что в интерфейсе A прописано, что свойство id может быть только строкой или числом, но в интерфейсе B прописано, что id: boolean.

>  как это связано с твоей ошибкой

В интерфейсе SwiperSlideProps указано, что children должен иметь тип ReactNode, а я передаю другой тип. И как я дальше поняла из этих логов:
```shell
➤ YN0000: │              Type '(slideData: SlideData) => ReactNode' is not assignable to type 'ReactNode'.
➤ YN0000: │                Type '(slideData: SlideData) => ReactNode' is missing the following properties from type 'ReactPortal': key, children, type, props
```
Не полуается привести к типу ReactNode из-за того, что не хватает каких-то свойств

**Comment by TFK70** [comment]
А почему у тебя в репе стоит 17 реакт, а типы для 18? https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-3/package.json#L12

**Comment by eshevlyakova** [comment]
@TFK70 
> А почему у тебя в репе стоит 17 реакт, а типы для 18?

Если я пишу @types/react: 17 [на это место](https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-3/package.json#L12), то в консоли при запуске сайта (yarn workspace @landing/renderer-entrypoint run dev) появляется такая ошибка:
```shell
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

It looks like you're trying to use TypeScript but do not have the required package(s) installed.

Please install @types/react by running:

        npm install --save-dev @types/react

If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files in your pages directory).
```
<img width="1256" alt="Снимок экрана 2022-10-28 в 15 19 33" src="https://user-images.githubusercontent.com/79781486/198585421-24b3bc38-5393-4f87-91ad-625193220528.png">

**Comment by TFK70** [comment]
@eshevlyakova попробуй версию `17.0.47`
