### ISSUE TITLE
Иконка внутри компонента Button

### ISSUE THREAD

**Issue by eshevlyakova** [atls-academy/eshevlyakova.github.io#25]
### Скоуп

Добавление attachment в @ui/button

### Описание

Не получается реализовать возможность добавление иконки одной строчкой. Сайт запускается без ошибок, но иконка не добавляется внутрь кнопки.

### Контекст

[Кнопка в которую хочу добавить иконку](https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-3/landing/fragments/landing-section-courses/src/courses.component.tsx#L49)
[Сам attachment](https://github.com/atls-academy/eshevlyakova.github.io/tree/feat/landing-step-3/ui/button/src/right-attachment)

### Воспроизведение

1. Идем в ui/button/src/right-attachment - это весь добавленный код, делала по [примеру](https://github.com/torin-asakura/VSBLE/tree/master/ui/input/src/search-attachment)
2. Идем в landing/fragments/landing-section-courses/src/courses.component.tsx 46 строка - для этой кнопки я хочу добавить иконку
3. Запускаем сайт -  yarn workspace @landing/renderer-entrypoint run dev
4. Скроллим до последней секции и видим, что у кнопки "Все материалы" стрелка не добавилась 

### Ожидаемое поведение

Стрелка добавляется внутрь кнопки

### Медиа-материалы

<img width="961" alt="Снимок экрана 2022-11-02 в 13 18 33" src="https://user-images.githubusercontent.com/79781486/199464623-9f160619-4458-48ee-86d8-322dae0049fa.png">

### Действия

1. Смотрела пример реализации

### Вопрос

1. Из-за чего не работает?
2. Как правильно передавать проп icon в button.component.tsx? (мне кажется в этом файле ошибка)

**Comment by TFK70** [comment]
https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-3/ui/button/src/button.component.tsx#L27

Ты тут получаешь icon не из props, а из третьего аргумента коллбека в forwardRef, которого, насколько мне известно, не существует

**Comment by eshevlyakova** [comment]
> Ты тут получаешь icon не из props

А как его получать из props? Если [тут](https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-3/ui/button/src/button.component.tsx#L42) прописываю: 
```tsx
<RightAttachment icon={props.icon} />
```
То это не работает. При запуске сайта появляется такая ошибка (в консоли нет):
<img width="951" alt="Снимок экрана 2022-11-02 в 19 17 31" src="https://user-images.githubusercontent.com/79781486/199543656-ff1a348b-9c3c-4f11-97a3-59fd613393c2.png">
Она появилась из за того, что я передала объект с ключами, хотя рассчитывала, что там будет строка (в данном случае [arrow-right](https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-3/landing/fragments/landing-section-courses/src/courses.component.tsx#L49))

**Comment by TFK70** [comment]
@eshevlyakova она появилась из-за того, что ты вместо реакт компонента в children передаёшь объект

Посмотри на эту строку внимательнее - https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-3/ui/button/src/right-attachment/right-attachment.component.tsx#L14

**Comment by eshevlyakova** [comment]
Исправила ошибку, заменив [эту строку](https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-3/ui/button/src/right-attachment/right-attachment.component.tsx#L14) на:
```tsx
const Attachment = useMemo(() => styled(ConditionalRender())(), [])
```
Теперь стрелка добавляется внутрь Button
