### ISSUE TITLE
Знакомство с TypeScript

### ISSUE THREAD

**Issue by TFK70** [atls-academy/eshevlyakova.github.io#3]
### Задача

Ознакомиться с азами работы с языками программирования на примере TypeScript, научиться покрывать простые кейсы по автоматизации задач с помощью ЯП и выполнить задание

### План

- [x] Переменные и типы данных
- [x] Структуры данных
- [x] Условия
- [x] Циклы
- [x] Функции
- [x] Работа с ошибками
- [x] База Advanced JS API (методы массивов)

### Задание

Необходимо реализовать простой механизм авторизации. Должны быть удовлетворены следующие требования:

- [x] Должны присутствовать функции для регистрации:
- `login(username, password)` - вход
-  `logout()` - выход
- `register(username, password)` - регистрация
- `whoami()` - получение авторизованного на данный момент пользователя (сессии)
- [x] При регистрации должна быть проверка: логин должен быть не короче 5 символов, пароль должен быть не короче 6. Если условие не выполняется - выбрасывать ошибку
- [x] Должна быть возможность хранить креды (`credentials`) для нескольких пользователей
- [x] При попытке сделать логаут без активной сессии - должна выбрасываться ошибка
- [x] При попытке сделать `whoami` без активной сессии - выбрасывать ошибку
- [x] При удачном вызове `whoami` в консоли должен быть вывод логина пользователя, который авторизован в данный момент
- [x] При попытке сделать регистрацию/логин в момент, когда уже есть активная сессия - выбрасывать ошибку
- [x] Все данные должны быть типизированы: аргументы функций, используемые переменные, возвращаемые функциями значения

**Требования к обработке ошибок:**

Ошибки (и код в целом) не должны содержать символов кириллицы, при этом в некоторых ошибках должны использоваться [шаблонные строки](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Template_literals). Пример:

`User with login Dassfgfd not found`

`Password for user Johnathan is incorrect`

### Требования к оформлению задания

Задание должно быть выполнено в отдельной ветке. К этой ветке должен быть создан pull request. Если pull request еще не готов к мержу в мастер - он должен быть помечен как draft. Код должен удовлетворять проверкам lint и typecheck (`yarn lint`, `yarn typecheck`)

**Comment by eshevlyakova** [comment]
Несколько пока вопросов:
- Я же получается могу переделать сборку gulp под typescript, и с ним писать?
- Есть ли максимальные сроки у этой задачи?

**Comment by TFK70** [comment]
@eshevlyakova 

> Я же получается могу переделать сборку gulp под typescript, и с ним писать?

gulp здесь не нужен, достаточно просто использовать tsc для сборки тайпскрипта

> Есть ли максимальные сроки у этой задачи?

"В рамках разумного", жестких сроков нет

**Comment by eshevlyakova** [comment]
@TFK70
> gulp здесь не нужен, достаточно просто использовать tsc для сборки тайпскрипта
Я просто привыкла использовать pug и sass, а здесь все же придется писать стили и разметку

**Comment by eshevlyakova** [comment]
@TFK70 
> gulp здесь не нужен, достаточно просто использовать tsc для сборки тайпскрипта

Я просто привыкла использовать pug и sass, а здесь все же придется писать стили и разметку. Можно использовать gulp?

**Comment by TFK70** [comment]
> Я просто привыкла использовать pug и sass, а здесь все же придется писать стили и разметку.

Это если что задание исключительно на изучение тайпскрипта. Здесь не нужно ничего верстать и тому подобное, просто написать `.ts` файл

**Comment by eshevlyakova** [comment]
@TFK70 
То есть не нужна сама html форма? Нужно сдать один только .ts файл?

**Comment by TFK70** [comment]
@eshevlyakova 

> То есть не нужна сама html форма? Нужно сдать один только .ts файл?

Да, в задании ничего и не было про формы, html и т.п.

> И как мне сдать задание: с помощью pull request?

Да, только именуй ветки и коммиты по конвенции (это то, что ты читала в самом начале)

> создать папку task1 и в нем файл .ts

Тут делай как удобнее, в последствии все-равно мы будем это переводить на наш стек, так что файлы можешь хоть в корень кинуть

**Comment by eshevlyakova** [comment]
@TFK70 

> Должна быть возможность хранить креды (credentials) для нескольких пользователей

А данные нескольких пользователей где должны храниться и каком формате?

**Comment by TFK70** [comment]
@eshevlyakova 

> А данные нескольких пользователей где должны храниться и каком формате?

Пока просто в оперативной памяти

Формат используй какой удобнее

**Comment by eshevlyakova** [comment]
@TFK70
Проверка `yarn typecheck` работает, а проверка `yarn lint` нет. Пишут, что:
`Cannot find module '/Users/j_sh/Desktop/ts/eshevlyakova.github.io/task-1/.pnp.cjs'
➤ YN0000: │ Require stack:
➤ YN0000: │ - internal/preload`

**Comment by TFK70** [comment]
@eshevlyakova https://github.com/atls/convention/wiki/%D0%9E%D1%82%D0%BB%D0%B0%D0%B4%D0%BA%D0%B0-%D0%BA%D0%BE%D0%B4%D0%B0

**Comment by eshevlyakova** [comment]
@TFK70 
>object, нужно типизировать

А как именно его типизировать? Если у меня переменная credentials принимает объекты

**Comment by TFK70** [comment]
@eshevlyakova у объектов которые хранятся в credentials тоже есть определенный тип, допустим такой:

```typescript
interface User {
   username: string
   password: string
}
```

Чтобы типизировать массив из этих значений можно написать либо так `User[]`, либо так `Array<User>`

[Дока](https://www.typescriptlang.org/docs/handbook/basic-types.html#array)

**Comment by eshevlyakova** [comment]
Ознакомилась с основами TypeScript и выполнила задание
