### ISSUE TITLE
Миграция на tools

### ISSUE THREAD

**Issue by TFK70** [atls-academy/eshevlyakova.github.io#6]
### Какого рода задача?

Мигрировать авторизацию на tools

### Что и где будем менять?

Для сборки приложения необходимо использовать `yarn service build`, для запуска в дев режиме -  `yarn service dev`

Необходимо оформить task-1 как пакет (воркспейс) с определенной структурой: директория `src` и `index.ts` внутри - [пример](https://github.com/torin-asakura/misik/blob/master/ui/copy/package.json)

Внутри `package.json` должны находится скрипты для запуска проекта - `build`, `dev` и `start`

`build` билдит проект через `yarn service build` и кладет js в папку `dist`
`dev` запускает проект в dev режиме
`start` запускает уже сбилженный проект (`node dist/index.js`)

[Краткий обзор tools](https://github.com/atls/tools/wiki)

### Укажите референс

Приведение проекта к общему стеку

Пример прилоения, собирающегося с помощью  `yarn service` - https://github.com/atls/orbitto/blob/feat/init-backend/ligaments/entrypoints/service-entrypoint/package.json

Пример библиотеки, которая будет публиковаться в npm регистр - https://github.com/atls/nextjs/blob/master/packages/next-sitemap-generator/package.json

**Comment by eshevlyakova** [comment]
@TFK70

Несколько вопросов:
- Нужно использовать gulp/webpack для ts или все также команда tsc?
- Получается в task 1 у меня должно получится похожее: https://github.com/atls/template?

**Comment by TFK70** [comment]
@eshevlyakova 

> Нужно использовать gulp/webpack для ts или все также команда tsc?

Тебе не нужно настраивать инструменты для сборки проекта вручную. В этом и есть смысл tools, вся конфигурация находится "под капотом", тебе нужно только его команды выполнять

Tools использует webpack, на их странице в вики (которую я кидал) есть ссылка не его in-built конфиг

> Получается в task 1 у меня должно получится похожее: https://github.com/atls/template?

У тебя уже похожее. Твой репозиторий был создан из темплейта, я кинул примеры на что он должен быть похож task-1

И переименуй его пожалуйста в first-task и что-то типа, цифры в названиях воркспейсов лучше не используй

**Comment by eshevlyakova** [comment]
@TFK70

А есть какие-то документации по созданию пакетов? Потому что я вообще не понимаю, что делать дальше) Вот так выглядит мой package.json:

`{
  "name": "@eshevlyakova.github.io/first-task",
  "version": "0.0.1",
  "main": "src/index.ts",
  "bin": {
    "gen-sitemap": "./dist/index.js"
  },
  "files": [
    "dist"
  ],
  "scripts": {
    "build": "yarn service build",
    "dev": "yarn service dev",
    "start": "node dist/index.js"
  },
  "devDependencies": {
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0"
  }
}`

**Comment by eshevlyakova** [comment]
@TFK70

- Получается я пишу файл package.json и все будет работать? Дополнительно нигде, ничего менять не нужно?
- И насчет вызова команд: я к примеру пишу yarn start и должен выполниться js файл?

**Comment by TFK70** [comment]
@eshevlyakova 

> Получается я пишу файл package.json и все будет работать? Дополнительно нигде, ничего менять не нужно?

Приводишь проект к нужной структуре, оформляешь package.json и да, тогда скрипты будут работать

> И насчет вызова команд: я к примеру пишу yarn start и должен выполниться js файл?

Если ты предварительно проект сбилдила - то да
