### ISSUE TITLE
Создание пакета

### ISSUE THREAD

**Issue by eshevlyakova** [atls-academy/eshevlyakova.github.io#7]
### Скоуп

Создание файла package.json

### Описание

Не знаю, что дальше писать в файле

### Воспроизведение

```json
{
  "name": "@eshevlyakova.github.io/first-task",
  "version": "0.0.1",
  "main": "src/index.ts",
  "bin": {
    "gen-sitemap": "./dist/index.js"
  },
  "files": [
    "dist"
  ],
  "scripts": {
    "build": "yarn service build",
    "dev": "yarn service dev",
    "start": "node dist/index.js"
  },
  "devDependencies": {
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0"
  }
}
```

### Ожидаемое поведение

build - билдит проект через yarn service build и кладет js в папку dist
dev - запускает проект в dev режиме
start - запускает уже сбилженный проект (node dist/index.js)

### Действия

- Создала папку src и вней файл index.ts
- Создала файл package.json

### Вопрос

А есть какие-то документации по созданию пакетов?

**Comment by TFK70** [comment]
@eshevlyakova 

https://classic.yarnpkg.com/lang/en/docs/workspaces/

**Comment by eshevlyakova** [comment]
https://github.com/atls-academy/eshevlyakova.github.io/issues/8
