### ISSUE TITLE
Создание файла package.json

### ISSUE THREAD

**Issue by eshevlyakova** [atls-academy/eshevlyakova.github.io#8]
### Скоуп

Миграция на tools

### Описание

Не могу заполнить файл package.json

### Контекст

1. Привела папку first-task к нужной структуре (src/index.ts)
2. Создала файл package.json
3. Указала точку входа - "main": "src/index.ts"
4. Указала в scripts что должны делать определенные команды

### Воспроизведение

```json 
{
  "name": "@eshevlyakova.github.io/first-task",
  "private": true,
  "version": "0.0.1",
  "main": "src/index.ts",
  "scripts": {
    "build": "yarn service build",
    "dev": "yarn service dev",
    "start": "node dist/index.js"
  }
}
```

### Ожидаемое поведение

build - билдит проект через yarn service build и кладет js в папку dist
dev - запускает проект в dev режиме
start - запускает уже сбилженный проект (node dist/index.js)

### Действия

1. Читала статьи про package.json и его свойства
2. Смотрела примеры оформления пакетов

### Вопрос

- А откуда нужно вызывать команды (к примеру yarn start): с папки first-task или с главной папки (eshevlyakova.github.io)?
- Нужно что-то добавлять в файл или наоборот убирать лишнее?

**Comment by eshevlyakova** [comment]
1. Запустила команду yarn install для папки eshevlyakova.github.io
2. При записке команды yarn build появилась ошибка `Usage Error: The nearest package directory (/Users/j_sh/Desktop/study/eshevlyakova.github.io/first-task) doesn't seem to be part of the project declared in /Users/j_sh/Desktop/study/eshevlyakova.github.io.`
3. Исправила с помощью touch yarn.lock
4. И снова при запуске команды yarn build появляется новая ошибка: 
`
 Cannot find module '/Users/j_sh/Desktop/study/eshevlyakova.github.io/first-task/.pnp.cjs'
➤ YN0000: │ Require stack:
➤ YN0000: │ - internal/preload
`
Начала гуглить как ее исправить. Единственное решение, которое я нашла - это установить пакеты глобально, но это не подходящее решение

**Comment by TFK70** [comment]
@eshevlyakova 


Скрипты нужно выполнять с помощью команды `yarn workspace <название воркспейса> <команда>`

`cd` использовать не нужно

Это еще к ответу на вопрос ниже

> А откуда нужно вызывать команды (к примеру yarn start): с папки first-task или с главной папки (eshevlyakova.github.io)?

Все нужно выполнять из корня проекта

> Нужно что-то добавлять в файл или наоборот убирать лишнее?

"Что-то" - это что?

**Comment by eshevlyakova** [comment]
@TFK70 
> Скрипты нужно выполнять с помощью команды yarn workspace <название воркспейса> <команда>

Команда это к примеры build, start?
Как я поняла в моем случае workspace будет папка first-task, это значит что в корне проекта в файле package.json мне нужно создать данный workspace?

> "Что-то" - это что?

Какие-то еще свойства, код в общем

**Comment by TFK70** [comment]
@eshevlyakova 

> Как я поняла в моем случае workspace будет папка first-task, это значит что в корне проекта в файле package.json мне нужно создать данный workspace?

Название воркспейса указывается [тут](https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/migration-to-tools/first-task/package.json#L2). И мы не называем воркспейсы по названию репозитория, они называются в соответствии со своим скоупом. В твоем случае скоуп - это first-task. Я бы на твоем месте назвал его как-нибудь `@first-task/main`, или `@first-task/entrypoint`

> Команда это к примеры build, start?

Это скрипты, которые ты указываешь в пекедже. Помимо них у ярна есть свой набор команд. Например если тебе в твой воркспейс с first-task нужно будет добавить пакет - просто нужно выполнить в корне `yarn workspace @first-task/main add walker`, вместо того чтобы куда-то `cd`'шиться. Все можно делать прямо из корня.

> Какие-то еще свойства, код в общем

Поконкретнее? Зачем туда что-то добавлять?

**Comment by eshevlyakova** [comment]
@TFK70
> Поконкретнее? Зачем туда что-то добавлять?

Некорректно задала вопрос. Пока стало понятнее, спасибо. Буду делать

**Comment by eshevlyakova** [comment]
@TFK70 
> Это скрипты, которые ты указываешь в пекедже.

То есть чтобы запустить скрипт build нужно написать: `yarn workspace @first-task/main run build`

**Comment by TFK70** [comment]
@eshevlyakova да

**Comment by eshevlyakova** [comment]
@TFK70 
А воркспейсы создаются так:  `"workspaces": ["@first-task/main"]`?

**Comment by TFK70** [comment]
@eshevlyakova попробуй

**Comment by eshevlyakova** [comment]
Попробовала, ошибка:
`Usage Error: Workspace '@first-task/main' not found. Did you mean any of the following:
  - template?` 
А можешь пожалуйста прислать статью на эту тему, я просто, которые сама находила там с помощью этого метода создавали

**Comment by eshevlyakova** [comment]
@TFK70 
Попробовала, ошибка:
`Usage Error: Workspace '@first-task/main' not found. Did you mean any of the following:
template?`

А можешь пожалуйста прислать статью на эту тему, я просто, которые сама находила там с помощью этого метода создавали

**Comment by TFK70** [comment]
@eshevlyakova 

https://classic.yarnpkg.com/lang/en/docs/workspaces/

> Add the following in a package.json file. Starting from now on, we’ll call this directory the “workspace root”:
```json
{
  "private": true,
  "workspaces": ["workspace-a", "workspace-b"]
}
```
> Note that the private: true is required! Workspaces are not meant to be published, so we’ve added this safety measure to make sure that nothing can accidentally expose them.

> After this file has been created, create two new subfolders named workspace-a and workspace-b. In each of them, create another package.json file with the following content:

**workspace-a/package.json:**
```json
{
  "name": "workspace-a",
  "version": "1.0.0",

  "dependencies": {
    "cross-env": "5.0.5"
  }
}
```

В корневом пекедже указываются не названия твоих воркспейсов, а директории, в которых их нужно резолвить

К тому же пример можно было посмотреть в [репозитории](https://github.com/atls/orbitto/blob/feat/init-backend/package.json), который я тебе кидал в задаче

**Comment by eshevlyakova** [comment]
Я создала и заполнила файл package.json
